name: Build & Test

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.202
    - name: Build
      run: dotnet build --configuration Release --nologo
    - name: Test
      run: dotnet test --configuration Release --no-build --nologo 
      
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1